#!/bin/bash
cd ${0%/*} || exit 1    # Run from this directory

mkdir bin
mkdir build

DIR=$(pwd)

# https://github.com/pybind/pybind11/issues/2127
cmake -S . -B build \
      -D CMAKE_INSTALL_PREFIX:PATH="${DIR}\bin" \ 
      -D PYTHON_EXECUTABLE:PATH="${DIR}\pybind11-env\Scripts\python.exe" \
      -D pybind11_DIR:PATH="${DIR}\extern\pybind11\build\lib\pybind11\share\cmake\pybind11" \
      -D Qt5_DIR:PATH="C:\Applications\Qt\Qt5.14.2\5.14.2\msvc2017_64\lib\cmake\Qt5" \
      -D Qt5_BIN_DIR:PATH="C:\Applications\Qt\Qt5.14.2\5.14.2\msvc2017_64\bin"

cmake --build build --config Release

cmake --install build --config Release